name: pharmaray
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dots_indicator:
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  firebase_core: ^2.8.0
  firebase_core_platform_interface: ^4.5.3
  firebase_messaging: 14.2.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: 13.0.0
  flutter_multi_formatter: ^2.4.1
  flutter_phoenix: ^1.1.0
  flutter_screenutil: ^5.0.2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.2
  google_fonts:
  google_maps_flutter: ^2.1.2
  image_picker: ^0.8.6
  internet_connection_checker: ^0.0.1+1
  intl:
  jiffy: ^5.0.0
  loading_animation_widget: ^1.1.0+1
  logger: ^1.1.0
  lottie: ^1.4.3
  permission_handler: 10.0.0
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.3.0
  readmore: ^2.2.0
  shimmer:
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dummy/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/appLogo.jpg"
  remove_alpha_ios: true