name: pharmaray
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dots_indicator:
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  firebase_core: ^2.24.0
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  flutter_multi_formatter: ^2.4.1
  flutter_phoenix: ^1.1.0
  flutter_screenutil: ^5.0.2
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  get: ^4.6.1
  get_storage: ^2.0.2
  google_fonts:
  google_maps_flutter: ^2.1.2
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl:
  jiffy: ^6.2.1
  loading_animation_widget: ^1.1.0+1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.3.5
  readmore: ^2.2.0
  shimmer:
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/dummy/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/appLogo.jpg"
  remove_alpha_ios: true